services:
  rto_consultas_dev:
    container_name: rto_consultas_dev
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ./envfiles/.env
    ports:
      - "${WEB_PORT}:8000"  #Web port 
    volumes: 
      - .:/home/code
    restart: unless-stopped
    command: ["/home/code/entrypoint.sh"]

  rto_memcached:
    container_name: rto_memcached
    depends_on:
      - rto_consultas_dev
    image: memcached:latest
    restart: unless-stopped
    ports:
      - 11211:11211
    command:
      - '--memory-limit=1024'
