services:
  rto_consultas_prod:
    container_name: rto_consultas
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ./envfiles/.env.prod
    ports:
      - "${WEB_PORT}:8000"  #Web port 
    # volumes:
    #   - .:/home/code
    restart: unless-stopped
    command: ["/home/code/entrypoint.sh"]

