services:
  rto_consultas_prod:
    container_name: rto_consultas_prod
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: ./envfiles/.env.prod
    # ports:
    #   - "${WEB_PORT}:8000"  #Web port
    # volumes:
    #   - .:/home/code
    restart: unless-stopped
    command: ["/home/code/entrypoint_prod.sh"]

  rto_consultas_web_server:
    container_name: rto_consultas_web_server
    depends_on:
      - rto_consultas_prod
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certificates:/etc/nginx/certificates
      - ./staticfiles:/home/code/staticfiles:ro
