# Generated by Django 4.1.7 on 2023-06-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.AddIndex(
            model_name='vwverificaciones',
            index=models.Index(fields=['idverificacion', 'idtaller'], name='vw_verifica_idVerif_5bf889_idx'),
        ),
        migrations.AddIndex(
            model_name='vwverificaciones',
            index=models.Index(fields=['idtipouso'], name='vw_verifica_idTipoU_178392_idx'),
        ),
        migrations.AddIndex(
            model_name='vwverificaciones',
            index=models.Index(fields=['idhabilitacion'], name='vw_verifica_idHabil_f6ed0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vwverificaciones',
            unique_together={('idverificacion', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='verificacionesservicios',
            unique_together={('idverificacionesservicios', 'idtaller', 'idservicio')},
        ),
        migrations.AlterUniqueTogether(
            name='verificacionespdf',
            unique_together={('idpdf', 'idtaller')},
        ),
        migrations.AddField(
            model_name='verificacionesdefectos',
            name='idnivel',
            field=models.ForeignKey(db_column='idNivel', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.nivelesdefectos'),
        ),
        migrations.AddField(
            model_name='verificacionesdefectos',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.talleres'),
        ),
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idverificacion', 'idtaller'], name='verificacio_idVerif_fd9b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idtipouso'], name='verificacio_idTipoU_194eff_idx'),
        ),
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idhabilitacion'], name='verificacio_idHabil_2efd7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='verificaciones',
            unique_together={('idverificacion', 'idtaller')},
        ),
        migrations.AddField(
            model_name='usuariostaller',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.talleres'),
        ),
        migrations.AlterUniqueTogether(
            name='pendientesservicios',
            unique_together={('idpendienteservicios', 'idtaller', 'idservicio')},
        ),
        migrations.AddField(
            model_name='pendientesdefectos',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.talleres'),
        ),
        migrations.AlterUniqueTogether(
            name='mantenimientos',
            unique_together={('idmantenimiento', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='lineastaller',
            unique_together={('nrolinea', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='instalaciones',
            unique_together={('idinstalacion', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='inspectores',
            unique_together={('idinspector', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='fotovalidacionpatente',
            unique_together={('idfotovalidacion', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='equipos',
            unique_together={('idequipo', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='direcotrestecnicos',
            unique_together={('iddirector', 'idtaller')},
        ),
        migrations.AddIndex(
            model_name='certificados',
            index=models.Index(fields=['idcertificado', 'idtaller'], name='certificado_idCerti_0534f7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificados',
            index=models.Index(fields=['idverificacion'], name='certificado_idVerif_6240c7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificados',
            index=models.Index(fields=['idtaller'], name='certificado_idTalle_041911_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificados',
            unique_together={('idcertificado', 'idtaller')},
        ),
        migrations.AddField(
            model_name='categoriastalleres',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.talleres'),
        ),
        migrations.AddField(
            model_name='auditoriasequipos',
            name='idequipo',
            field=models.ForeignKey(db_column='idEquipo', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.equipos'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativos',
            unique_together={('idadministrativo', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='verificacionesdefectos',
            unique_together={('idverificacion', 'idtaller', 'iddefecto')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariostaller',
            unique_together={('idusuario', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='pendientesdefectos',
            unique_together={('idpendiente', 'idtaller', 'iddefecto')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriastalleres',
            unique_together={('idcategoria', 'idtaller')},
        ),
        migrations.AlterUniqueTogether(
            name='auditoriasequipos',
            unique_together={('idauditoria', 'idtaller', 'idequipo')},
        ),
    ]
