# Generated by Django 4.1.7 on 2023-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='estados',
            index=models.Index(fields=['idestado'], name='estados_idEstad_585139_idx'),
        ),
        migrations.AddIndex(
            model_name='localidades',
            index=models.Index(fields=['idlocalidad'], name='localidades_idLocal_59324d_idx'),
        ),
        migrations.AddIndex(
            model_name='talleres',
            index=models.Index(fields=['idtaller'], name='talleres_idTalle_bb673b_idx'),
        ),
        migrations.AddIndex(
            model_name='tipousovehiculo',
            index=models.Index(fields=['idtipouso'], name='tipousovehi_idTipoU_0bd423_idx'),
        ),
        migrations.AddIndex(
            model_name='tipovehiculo',
            index=models.Index(fields=['idtipovehiculo'], name='tipovehicul_idTipoV_7331aa_idx'),
        ),
    ]
