# Generated by Django 4.2.3 on 2023-07-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0002_estados_estados_idestad_585139_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VWVerificaciones',
        ),
    ]
