# Generated by Django 4.2.3 on 2023-07-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0003_delete_vwverificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificados',
            name='idverificacion',
            field=models.ForeignKey(db_column='idVerificacion', on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='rto_consultas.verificaciones'),
        ),
    ]
