# Generated by Django 4.2.3 on 2023-07-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0004_alter_certificados_idverificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estados',
            name='idestado',
            field=models.AutoField(db_column='idEstado', primary_key=True, serialize=False, verbose_name='Estado Certificado'),
        ),
        migrations.AlterField(
            model_name='talleres',
            name='idtaller',
            field=models.AutoField(db_column='idTaller', primary_key=True, serialize=False, verbose_name='Taller'),
        ),
        migrations.AlterField(
            model_name='tipousovehiculo',
            name='idtipouso',
            field=models.AutoField(db_column='idTipoUso', primary_key=True, serialize=False, verbose_name='Tipo Uso'),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='dominio',
            field=models.CharField(db_column='Dominio', max_length=10, primary_key=True, serialize=False, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='verificaciones',
            name='fecha',
            field=models.DateField(db_column='Fecha', verbose_name='Fecha'),
        ),
    ]
