# Generated by Django 4.2.3 on 2023-07-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0005_alter_estados_idestado_alter_talleres_idtaller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificaciones',
            name='dominiovehiculo',
            field=models.ForeignKey(db_column='DominioVehiculo', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.vehiculos', verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='verificaciones',
            name='idtaller',
            field=models.ForeignKey(db_column='idTaller', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.talleres', verbose_name='Taller'),
        ),
    ]
