# Generated by Django 4.2.3 on 2023-07-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0006_alter_verificaciones_dominiovehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificaciones',
            name='idestado',
            field=models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='rto_consultas.estados', verbose_name='Estado Certificado'),
        ),
        migrations.AlterField(
            model_name='verificaciones',
            name='idtipouso',
            field=models.IntegerField(db_column='idTipoUso', verbose_name='Tipo de Uso'),
        ),
    ]
