# Generated by Django 4.2.3 on 2023-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0007_alter_verificaciones_idestado_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificaciones',
            name='verificacio_idTipoU_194eff_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificaciones',
            name='verificacio_idHabil_2efd7e_idx',
        ),
        migrations.AlterField(
            model_name='verificaciones',
            name='idtipovehiculo',
            field=models.IntegerField(blank=True, db_column='idTipoVehiculo', null=True, verbose_name='Tipo de Vehiculo'),
        ),
    ]
