# Generated by Django 4.2.3 on 2023-07-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto_consultas', '0008_remove_verifs.py'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idtipouso'], name='verificacio_idTipoU_194eff_idx'),
        ),
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idhabilitacion'], name='verificacio_idHabil_2efd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idestado'], name='verificacio_idEstad_e2862f_idx'),
        ),
        migrations.AddIndex(
            model_name='verificaciones',
            index=models.Index(fields=['idtipovehiculo'], name='verificacio_idTipoV_b5bd8a_idx'),
        ),
    ]
