version: "3.7"
services:
  rto_mysql_db:
    image: mysql/mysql-server:latest
    container_name: rto_mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      - ${INIT_DB_PATH}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p${MYSQL_ROOT_PASSWORD} ping -h localhost
      interval: 20s
      timeout: 10s
      retries: 5

  rto_cron_mysql_bkp:
    image: fradelg/mysql-cron-backup
    container_name: rto_cron_mysql_bkp
    depends_on:
      - rto_mysql_db
    volumes:
      - "${BACKUP_PATH}:/backup"
    environment:
      - MYSQL_HOST=rto_mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MAX_BACKUPS=5
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 23 * * *
      # - CRON_TIME=* * * * *
      # Make it small
      - GZIP_LEVEL=9
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - "./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus

  central_mysql_exporter:
    image: prom/mysqld-exporter
    container_name: central_mysql_exporter
    depends_on:
      - central_mysql_db
    ports:
      - 9104:9104
    environment:
      - MYSQL_HOST=central_mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
        # - DATA_SOURCE_NAME=user1:123@(central_mysql_db:3306)/
      - DATA_SOURCE_NAME=$MYSQL_USER:$MYSQL_PASSWORD@(central_mysql_db:3306)/
    # volumes:
    #   - "./central_mysql_db/exporter/.my.cnf:/.my.cnf:rw"
    # network_mode: host

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    ports:
    - 3000:3000

volumes:
  grafana-data:
  prometheus-data:
  # central_bkp:
